// flow-typed signature: 2b959046026c91c4c204ab5248885740
// flow-typed version: <<STUB>>/luxon_v^0.2.3/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'luxon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'luxon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'luxon/build/cjs-browser/luxon' {
  declare module.exports: any;
}

declare module 'luxon/build/node/luxon' {
  declare module.exports: any;
}

declare module 'luxon/src/datetime' {
  declare module.exports: any;
}

declare module 'luxon/src/duration' {
  declare module.exports: any;
}

declare module 'luxon/src/errors' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/conversions' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/english' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/formats' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/formatter' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/locale' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/regexParser' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/tokenParser' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/util' {
  declare module.exports: any;
}

declare module 'luxon/src/info' {
  declare module.exports: any;
}

declare module 'luxon/src/interval' {
  declare module.exports: any;
}

declare module 'luxon/src/luxon' {
  declare module.exports: any;
}

declare module 'luxon/src/luxonFilled' {
  declare module.exports: any;
}

declare module 'luxon/src/settings' {
  declare module.exports: any;
}

declare module 'luxon/src/zone' {
  declare module.exports: any;
}

declare module 'luxon/src/zones/fixedOffsetZone' {
  declare module.exports: any;
}

declare module 'luxon/src/zones/IANAZone' {
  declare module.exports: any;
}

declare module 'luxon/src/zones/localZone' {
  declare module.exports: any;
}

// Filename aliases
declare module 'luxon/build/cjs-browser/luxon.js' {
  declare module.exports: $Exports<'luxon/build/cjs-browser/luxon'>;
}
declare module 'luxon/build/node/luxon.js' {
  declare module.exports: $Exports<'luxon/build/node/luxon'>;
}
declare module 'luxon/src/datetime.js' {
  declare module.exports: $Exports<'luxon/src/datetime'>;
}
declare module 'luxon/src/duration.js' {
  declare module.exports: $Exports<'luxon/src/duration'>;
}
declare module 'luxon/src/errors.js' {
  declare module.exports: $Exports<'luxon/src/errors'>;
}
declare module 'luxon/src/impl/conversions.js' {
  declare module.exports: $Exports<'luxon/src/impl/conversions'>;
}
declare module 'luxon/src/impl/english.js' {
  declare module.exports: $Exports<'luxon/src/impl/english'>;
}
declare module 'luxon/src/impl/formats.js' {
  declare module.exports: $Exports<'luxon/src/impl/formats'>;
}
declare module 'luxon/src/impl/formatter.js' {
  declare module.exports: $Exports<'luxon/src/impl/formatter'>;
}
declare module 'luxon/src/impl/locale.js' {
  declare module.exports: $Exports<'luxon/src/impl/locale'>;
}
declare module 'luxon/src/impl/regexParser.js' {
  declare module.exports: $Exports<'luxon/src/impl/regexParser'>;
}
declare module 'luxon/src/impl/tokenParser.js' {
  declare module.exports: $Exports<'luxon/src/impl/tokenParser'>;
}
declare module 'luxon/src/impl/util.js' {
  declare module.exports: $Exports<'luxon/src/impl/util'>;
}
declare module 'luxon/src/info.js' {
  declare module.exports: $Exports<'luxon/src/info'>;
}
declare module 'luxon/src/interval.js' {
  declare module.exports: $Exports<'luxon/src/interval'>;
}
declare module 'luxon/src/luxon.js' {
  declare module.exports: $Exports<'luxon/src/luxon'>;
}
declare module 'luxon/src/luxonFilled.js' {
  declare module.exports: $Exports<'luxon/src/luxonFilled'>;
}
declare module 'luxon/src/settings.js' {
  declare module.exports: $Exports<'luxon/src/settings'>;
}
declare module 'luxon/src/zone.js' {
  declare module.exports: $Exports<'luxon/src/zone'>;
}
declare module 'luxon/src/zones/fixedOffsetZone.js' {
  declare module.exports: $Exports<'luxon/src/zones/fixedOffsetZone'>;
}
declare module 'luxon/src/zones/IANAZone.js' {
  declare module.exports: $Exports<'luxon/src/zones/IANAZone'>;
}
declare module 'luxon/src/zones/localZone.js' {
  declare module.exports: $Exports<'luxon/src/zones/localZone'>;
}
