// flow-typed signature: ef0fb4fa49d8260fb03dad4ba2849c42
// flow-typed version: <<STUB>>/react-native-deprecated-custom-components_v^0.1.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-deprecated-custom-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-deprecated-custom-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-deprecated-custom-components/src/__tests__/NavigationContext-test' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/__tests__/NavigationEvent-test' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/__tests__/NavigationEventEmitter-test' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/__tests__/NavigationRouteStack-test' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/__tests__/NavigationTreeNode-test' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/buildStyleInterpolator' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/clamp' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/CustomComponents' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/EmitterSubscription' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/EventEmitter' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/EventSubscription' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/EventSubscriptionVendor' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/flattenStyle' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/guid' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/InteractionMixin' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/merge' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/mergeHelpers' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/mergeInto' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/NavigationContext' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/NavigationEvent' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/NavigationEventEmitter' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/NavigationRouteStack' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/NavigationTreeNode' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/Navigator' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/NavigatorBreadcrumbNavigationBar' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/NavigatorBreadcrumbNavigationBarStyles.android' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/NavigatorBreadcrumbNavigationBarStyles.ios' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/NavigatorNavigationBar' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/NavigatorNavigationBarStylesAndroid' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/NavigatorNavigationBarStylesIOS' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/NavigatorSceneConfigs' {
  declare module.exports: any;
}

declare module 'react-native-deprecated-custom-components/src/Subscribable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-deprecated-custom-components/src/__tests__/NavigationContext-test.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/__tests__/NavigationContext-test'>;
}
declare module 'react-native-deprecated-custom-components/src/__tests__/NavigationEvent-test.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/__tests__/NavigationEvent-test'>;
}
declare module 'react-native-deprecated-custom-components/src/__tests__/NavigationEventEmitter-test.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/__tests__/NavigationEventEmitter-test'>;
}
declare module 'react-native-deprecated-custom-components/src/__tests__/NavigationRouteStack-test.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/__tests__/NavigationRouteStack-test'>;
}
declare module 'react-native-deprecated-custom-components/src/__tests__/NavigationTreeNode-test.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/__tests__/NavigationTreeNode-test'>;
}
declare module 'react-native-deprecated-custom-components/src/buildStyleInterpolator.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/buildStyleInterpolator'>;
}
declare module 'react-native-deprecated-custom-components/src/clamp.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/clamp'>;
}
declare module 'react-native-deprecated-custom-components/src/CustomComponents.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/CustomComponents'>;
}
declare module 'react-native-deprecated-custom-components/src/EmitterSubscription.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/EmitterSubscription'>;
}
declare module 'react-native-deprecated-custom-components/src/EventEmitter.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/EventEmitter'>;
}
declare module 'react-native-deprecated-custom-components/src/EventSubscription.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/EventSubscription'>;
}
declare module 'react-native-deprecated-custom-components/src/EventSubscriptionVendor.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/EventSubscriptionVendor'>;
}
declare module 'react-native-deprecated-custom-components/src/flattenStyle.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/flattenStyle'>;
}
declare module 'react-native-deprecated-custom-components/src/guid.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/guid'>;
}
declare module 'react-native-deprecated-custom-components/src/InteractionMixin.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/InteractionMixin'>;
}
declare module 'react-native-deprecated-custom-components/src/merge.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/merge'>;
}
declare module 'react-native-deprecated-custom-components/src/mergeHelpers.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/mergeHelpers'>;
}
declare module 'react-native-deprecated-custom-components/src/mergeInto.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/mergeInto'>;
}
declare module 'react-native-deprecated-custom-components/src/NavigationContext.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/NavigationContext'>;
}
declare module 'react-native-deprecated-custom-components/src/NavigationEvent.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/NavigationEvent'>;
}
declare module 'react-native-deprecated-custom-components/src/NavigationEventEmitter.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/NavigationEventEmitter'>;
}
declare module 'react-native-deprecated-custom-components/src/NavigationRouteStack.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/NavigationRouteStack'>;
}
declare module 'react-native-deprecated-custom-components/src/NavigationTreeNode.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/NavigationTreeNode'>;
}
declare module 'react-native-deprecated-custom-components/src/Navigator.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/Navigator'>;
}
declare module 'react-native-deprecated-custom-components/src/NavigatorBreadcrumbNavigationBar.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/NavigatorBreadcrumbNavigationBar'>;
}
declare module 'react-native-deprecated-custom-components/src/NavigatorBreadcrumbNavigationBarStyles.android.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/NavigatorBreadcrumbNavigationBarStyles.android'>;
}
declare module 'react-native-deprecated-custom-components/src/NavigatorBreadcrumbNavigationBarStyles.ios.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/NavigatorBreadcrumbNavigationBarStyles.ios'>;
}
declare module 'react-native-deprecated-custom-components/src/NavigatorNavigationBar.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/NavigatorNavigationBar'>;
}
declare module 'react-native-deprecated-custom-components/src/NavigatorNavigationBarStylesAndroid.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/NavigatorNavigationBarStylesAndroid'>;
}
declare module 'react-native-deprecated-custom-components/src/NavigatorNavigationBarStylesIOS.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/NavigatorNavigationBarStylesIOS'>;
}
declare module 'react-native-deprecated-custom-components/src/NavigatorSceneConfigs.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/NavigatorSceneConfigs'>;
}
declare module 'react-native-deprecated-custom-components/src/Subscribable.js' {
  declare module.exports: $Exports<'react-native-deprecated-custom-components/src/Subscribable'>;
}
