// flow-typed signature: 0be92ef7cff21f2eac745db77a61222e
// flow-typed version: <<STUB>>/react-native-firebase-analytics_v^3.0.6/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-firebase-analytics'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-firebase-analytics' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-firebase-analytics/index' {
  declare module.exports: $Exports<'react-native-firebase-analytics'>;
}
declare module 'react-native-firebase-analytics/index.js' {
  declare module.exports: $Exports<'react-native-firebase-analytics'>;
}
